swagger: '2.0'

basePath: /
definitions:
  handler.errorResponse:
    properties:
      message:
        type: string
    type: object
  app.signInInput:
    properties:
      email:
        type: string
        example: 'boryslav.ziubrytskyi@gmail.com'
      password:
        type: string
        example: "qwerty123321"
    required:
      - email
      - password
    type: object
  User:
    properties:
      name:
        type: string
        example: 'Boryslav Ziubrytskyi'
      email:
        type: string
        example: 'boryslav.ziubrytskyi@gmail.com'
      password:
        type: string
        example: "qwerty123321"
    required:
      - name
      - email
      - password
    type: object
  Token:
    properties:
      token:
        type: string
        example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODQyMzY1NzUsImlhdCI6MTY4NDA2Mzc3NSwidXNlcl9pZCI6MX0.M35OqYQp8naY8DckGulHSsjuA4mvCM62qoB6nUDzFmY'
  Currency:
    type: object
    properties:
      txt:
        type: string
      code:
        type: string
      officialRate:
        type: string
      darkRate:
        type: string
host: localhost:8081
info:
  contact: { }
  description: API Server for Budget Tracker
  title: Budget Tracker App API
  version: "1.0"
paths:
  /auth/sign-in:
    post:
      consumes:
        - application/json
      description: login
      operationId: login
      parameters:
        - description: credentials
          in: body
          name: input
          required: true
          schema:
            $ref: '#definitions/app.signInInput'
      produces:
        - application/json
      responses:
        "200":
          description: token
          schema:
            $ref: '#/definitions/Token'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
          examples:
            application/json:
              message: invalid input body
        "404":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
          examples:
            application/json:
              message: not found
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: SignIn
      tags:
        - auth
  /auth/sign-up:
    post:
      consumes:
        - application/json
      description: create account
      operationId: create-account
      parameters:
        - description: account info
          in: body
          name: input
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        "200":
          description: token
          schema:
            $ref: '#/definitions/handler.errorResponse'
          examples:
            application/json:
              message: Success
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
          examples:
            application/json:
              message: invalid input body
        "419":
          description: Status Conflict
          schema:
            $ref: '#/definitions/handler.errorResponse'
          examples:
            application/json:
              message: user is already exists
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
          examples:
            application/json:
              message: something gone wrong while trying create user
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: SignUp
      tags:
        - auth
  /courses/getAll:
    get:
      consumes:
        - application/json
      description: get data from goverla and nbu
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/Currency"
            example:
              - txt: Долар США
                code: USD
                officialRate: "36.5686"
                darkRate: "37.77"
              - txt: Євро
                code: EUR
                officialRate: "39.8287"
                darkRate: "41.35"
              - txt: Злотий
                code: PLN
                officialRate: "8.785"
                darkRate: "9.0"
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
          examples:
            application/json:
              message: something gone wrong while trying create user
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
